"""Add subcategories and CSGORoll support

Revision ID: 35139339d798
Revises: 
Create Date: 2025-01-28 14:38:07.430638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35139339d798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_coins', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('purchase_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('fees')
        batch_op.drop_column('wear_level')
        batch_op.drop_column('profit')
        batch_op.drop_column('date_added')
        batch_op.drop_column('date_sold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_sold', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('profit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('wear_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fees', sa.FLOAT(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('purchase_source')
        batch_op.drop_column('purchase_coins')

    # ### end Alembic commands ###
