"""Update item model

Revision ID: 546e2fe9bddd
Revises: 35139339d798
Create Date: 2025-01-28 15:41:56.534079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546e2fe9bddd'
down_revision = '35139339d798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('paint_seed')
        batch_op.drop_column('special_type')
        batch_op.drop_column('purchase_coins')
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('purchase_coins', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('special_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('paint_seed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
